best_works/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page

from core.views import (
    AboutPageView,
    BadRequestView,
    ContactPageView,
    CsrfFailureView,
    PageNotFoundView,
)

urlpatterns = [
    path("jet/", include("jet.urls", "jet")),
    path(
        "jet/dashboard/",
        include("jet.dashboard.urls", "jet-dashboard"),
    ),
    path("", include("works.urls", namespace="works")),
    path(
        "about_us/",
        cache_page(settings.ABOUT_PAGE_CACHE_SECOND)(AboutPageView.as_view()),
        name="about_us",
    ),
    path("contacts/", ContactPageView.as_view(), name="contacts"),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )

handler400 = BadRequestView.as_view()
handler403 = CsrfFailureView.as_view()
handler404 = PageNotFoundView.as_view()
handler500 = "core.views.internal_server_error"

works/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page

from works.apps import WorksConfig
from works.views import HomePageView, ServiceView

app_name = WorksConfig.name

urlpatterns = [
    path(
        "",
        cache_page(settings.HOME_PAGE_CACHE_SECOND)(HomePageView.as_view()),
        name="home_page",
    ),
    path("services/", ServiceView.as_view(), name="services"),
]

templates/includes/desktop/navbar.html
<div class="uk-position-relative">
  <div class="uk-position-top">
    <nav class="uk-navbar-container uk-navbar-transparent">
      <div class="uk-container">
        <div uk-navbar class="uk-visible@m uk-text-bolder">
          <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
              {% url 'works:home_page' as url %}
              <li class="{% if request.path == url %}uk-active{% endif %}">
                <a href="{% url 'works:home_page' %}">Главная {{ url_name }}</a>
              </li>
              {% url 'about_us' as url %}
              <li class="{% if request.path == url %}uk-active{% endif %}">
                <a href="{% url 'about_us' %}">О Нас</a>
              </li>
              {% url 'works:services' as url %}
              <li class="{% if request.path == url %}uk-active{% endif %}">
                <a href="{% url 'works:services' %}">Услуги</a>
              </li>
              {% url 'contacts' as url %}
              <li class="{% if request.path == url %}uk-active{% endif %}">
                <a href="{% url 'contacts' %}">Контакты</a>
              </li>
            </ul>
          </div>
          <div class="uk-navbar-center">
            <div class="uk-panel uk-padding uk-background-secondary">
              <a class="uk-logo uk-text-middle uk-text-uppercase uk-text-warning"
                 href="{% url 'works:home_page' %}">{{ company.name|upper }}</a>
            </div>
          </div>
          <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
              <li class="">
                <a href="tel:{{ company.phone }}"
                   class="uk-text-emphasis"
                   uk-icon="icon: receiver"></a>
              </li>
              {% include 'includes/social_networks.html' %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>